# Generated by Django 5.1.1 on 2024-11-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_savedplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedclan',
            name='clan_tag',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='savedplayer',
            name='player_tag',
            field=models.CharField(max_length=20),
        ),
    ]
