# Generated by Django 5.1.3 on 2024-12-21 14:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_savedclan_clan_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_tag', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMonthlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(default=datetime.datetime.now)),
                ('barbarian_king_level', models.IntegerField()),
                ('archer_queen_level', models.IntegerField()),
                ('grand_warden_level', models.IntegerField()),
                ('minion_prince_level', models.IntegerField()),
                ('battle_machine_level', models.IntegerField()),
                ('battle_copter_level', models.IntegerField()),
                ('town_hall_level', models.IntegerField()),
                ('builder_hall_level', models.IntegerField()),
                ('clan_name', models.CharField(max_length=20)),
                ('clan_tag', models.CharField(max_length=20)),
                ('total_levels', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_data', to='main.globalplayer')),
            ],
        ),
    ]
