# Generated by Django 5.1.3 on 2024-12-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_globalplayer_playermonthlydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermonthlydata',
            name='hour',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='playermonthlydata',
            name='minute',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='playermonthlydata',
            name='second',
            field=models.IntegerField(default=7),
        ),
    ]
