# Generated by Django 5.1.3 on 2024-12-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_playermonthlydata_hour_playermonthlydata_minute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermonthlydata',
            name='royal_champion_level',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
