# Generated by Django 5.1.3 on 2024-12-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_playermonthlydata_royal_champion_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermonthlydata',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playermonthlydata',
            name='month',
            field=models.CharField(default='', max_length=20),
        ),
    ]
