# Generated by Django 5.1.3 on 2024-12-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_playermonthlydata_total_levels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermonthlydata',
            name='archer_queen_level',
        ),
        migrations.RemoveField(
            model_name='playermonthlydata',
            name='barbarian_king_level',
        ),
        migrations.RemoveField(
            model_name='playermonthlydata',
            name='battle_copter_level',
        ),
        migrations.RemoveField(
            model_name='playermonthlydata',
            name='battle_machine_level',
        ),
        migrations.RemoveField(
            model_name='playermonthlydata',
            name='grand_warden_level',
        ),
        migrations.RemoveField(
            model_name='playermonthlydata',
            name='minion_prince_level',
        ),
        migrations.RemoveField(
            model_name='playermonthlydata',
            name='royal_champion_level',
        ),
        migrations.AddField(
            model_name='playermonthlydata',
            name='equipment_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='playermonthlydata',
            name='hero_data',
            field=models.JSONField(default=list),
        ),
    ]
