# Generated by Django 5.1.3 on 2024-12-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_playermonthlydata_archer_queen_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermonthlydata',
            name='builder_base_trophies',
            field=models.IntegerField(default=0),
        ),
    ]
