# Generated by Django 5.1.3 on 2024-12-22 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_clanmonthlydatawar_average_stars_per_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanmonthlydatawar',
            name='month_year',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
