# Generated by Django 5.1.3 on 2024-12-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_clanmonthlydatawar_month_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanmonthlydatawar',
            name='percent_attacks_completed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clanmonthlydatawar',
            name='win_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
