# Generated by Django 5.1.3 on 2024-12-23 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_clanmonthlydatawar_current_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerwarinformation',
            old_name='attack_1_percent',
            new_name='attack_1_destruction',
        ),
        migrations.RenameField(
            model_name='playerwarinformation',
            old_name='attack_2_percent',
            new_name='attack_2_destruction',
        ),
    ]
