# Generated by Django 5.1.3 on 2024-12-23 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_attack_1_percent_playerwarinformation_attack_1_destruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermonthlydatawar',
            name='average_total_destruction',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='playermonthlydatawar',
            name='average_total_stars',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playermonthlydatawar',
            name='clan_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='playermonthlydatawar',
            name='clan_tag',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='playermonthlydatawar',
            name='current_time',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='playermonthlydatawar',
            name='month_year',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
