# Generated by Django 5.1.3 on 2024-12-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_playermonthlydatawar_average_total_destruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerwarinformation',
            name='num_missed_attacks',
            field=models.IntegerField(default=0),
        ),
    ]
