# Generated by Django 5.1.3 on 2024-12-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_playerwarinformation_num_missed_attacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermonthlydata',
            name='player_name',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
