# Generated by Django 5.1.3 on 2024-12-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_playermonthlydata_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanwarinformation',
            name='current_time',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
