# Generated by Django 5.1.3 on 2024-12-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_clanwarinformation_current_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanmonthlydatageneral',
            name='data',
            field=models.JSONField(default=list),
        ),
    ]
