# Generated by Django 5.1.3 on 2024-12-24 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_playermonthlydata_xp_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermonthlydata',
            name='day_fetched',
        ),
        migrations.AddField(
            model_name='clanmonthlydatageneral',
            name='time_fetched',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='playermonthlydata',
            name='time_fetched',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
