# Generated by Django 5.1.3 on 2025-01-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_playermonthlydata_day_fetched'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanwarinformation',
            name='point_fetched',
            field=models.CharField(default='+4', max_length=50),
        ),
    ]
